package com.example.feedreader.util;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class FeedUtilsTest {
    @Test
    public void testGetPayload() {
        assertTrue(FeedUtils.getPayload("Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|42").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\42").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("##\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|#").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#\\|42").isEmpty());
        assertTrue(FeedUtils.getPayload("Message\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Message#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Message\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Message#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Message\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\|42").isEmpty());
        assertTrue(FeedUtils.getPayload("42\\").isEmpty());
        assertTrue(FeedUtils.getPayload("42#|").isEmpty());
        assertTrue(FeedUtils.getPayload("42\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("42#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("42\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostNot all who wander are lost\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostNot all who wander are lost#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostNot all who wander are lost\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostNot all who wander are lost#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostNot all who wander are lost\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\#").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\Message").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\42").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#|42").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\#").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\Message").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\\\42").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost##\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|#").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost#\\|42").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostMessage\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostMessage#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostMessage\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostMessage#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lostMessage\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|#").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost\\|42").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost42\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost42#|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost42\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost42#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("Not all who wander are lost42\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lostNot all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lost\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lost#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lost\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lost#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lost#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lostMessage").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lost\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Not all who wander are lost42").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#|42").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\\\42").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\##|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\##").isEmpty());
        assertTrue(FeedUtils.getPayload("\\##\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#42").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\#\\|42").isEmpty());
        assertTrue(FeedUtils.getPayload("\\MessageNot all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Message\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Message#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Message\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Message#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Message#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\MessageMessage").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Message\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\Message42").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\\\|42").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42#|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42#").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42Message").isEmpty());
        assertTrue(FeedUtils.getPayload("\\42\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("\\4242").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lostNot all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lost\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lost#|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lost\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lost#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lostMessage").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lost\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Not all who wander are lost42").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\#|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\#").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\Message").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\42").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#|42").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\#|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\#").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\Message").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|\\\\42").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|##\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|Not all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|#|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|\\\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|#").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|#\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|Message").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|\\|").isEmpty());
        assertTrue(FeedUtils.getPayload("#|#\\|42").isEmpty());
        assertTrue(FeedUtils.getPayload("#|MessageNot all who wander are lost").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Message\\").isEmpty());
        assertTrue(FeedUtils.getPayload("#|Message#|").isEmpty());
    }
}

